### ISSUE TITLE
Flea not working

### ISSUE THREAD

**Issue by Vistaus** [addy-dclxvi/Conky-Theme-Collections#1]
Thank you so much for that beautiful Flea conky! Just saw it on Reddit (Unixporn) and I want to use it so badly! But I can't because conky thinks it contains a lot of errors. I'm not all that experienced with conky but I do have imlib2 installed. I've tried running conky with your config file specified as well as copying the content to /etc/conky/conky.conf (as you can see below) but both throw out the same errors. Would you please help me out? :)

The output is:
```
 ╭─vistaus@solus /run/media/vistaus/MicroSD/Apps  ‹system› 
╰─$ conky &
Conky: /etc/conky/conky.conf: 1: no such configuration: '--[['
Conky: /etc/conky/conky.conf: 14: no such configuration: ']]'
Conky: /etc/conky/conky.conf: 17: no such configuration: 'conky.config'
Conky: /etc/conky/conky.conf: 18: no such configuration: '--'
Conky: /etc/conky/conky.conf: 20: config file error
Conky: /etc/conky/conky.conf: 22: config file error
Conky: /etc/conky/conky.conf: 22: config file error
Conky: /etc/conky/conky.conf: 26: no such configuration: '--'
Conky: /etc/conky/conky.conf: 27: no such configuration: '--'
Conky: /etc/conky/conky.conf: 28: no such configuration: '--'
Conky: /etc/conky/conky.conf: 29: no such configuration: '--'
Conky: /etc/conky/conky.conf: 30: no such configuration: '--'
Conky: /etc/conky/conky.conf: 32: no such configuration: '--'
Conky: /etc/conky/conky.conf: 33: no such configuration: '--'
Conky: /etc/conky/conky.conf: 34: no such configuration: '--'
Conky: /etc/conky/conky.conf: 35: no such configuration: '--'
Conky: /etc/conky/conky.conf: 36: no such configuration: '--'
Conky: /etc/conky/conky.conf: 38: no such configuration: 'minimum_width'
Conky: /etc/conky/conky.conf: 39: no such configuration: 'minimum_height'
Conky: /etc/conky/conky.conf: 40: config file error
Conky: /etc/conky/conky.conf: 45: config file error
Conky: /etc/conky/conky.conf: 46: no such configuration: '--'
Conky: /etc/conky/conky.conf: 47: no such configuration: '--'
Conky: /etc/conky/conky.conf: 48: no such configuration: '--'
Conky: /etc/conky/conky.conf: 53: no such configuration: '--'
Conky: /etc/conky/conky.conf: 55: no such configuration: '--'
Conky: /etc/conky/conky.conf: 59: no such configuration: '--'
Conky: /etc/conky/conky.conf: 60: no such configuration: '--'
Conky: /etc/conky/conky.conf: 74: no such configuration: '--'
Conky: /etc/conky/conky.conf: 75: no such configuration: '--'
Conky: /etc/conky/conky.conf: 77: no such configuration: '--'
Conky: /etc/conky/conky.conf: 79: no such configuration: '--'
Conky: /etc/conky/conky.conf: 82: no such configuration: '--'
Conky: /etc/conky/conky.conf: 84: no such configuration: '--'
Conky: /etc/conky/conky.conf: 86: no such configuration: '--default_graph_size'
Conky: /etc/conky/conky.conf: 87: no such configuration: '--'
Conky: /etc/conky/conky.conf: 88: no such configuration: '--'
Conky: /etc/conky/conky.conf: 89: no such configuration: '--'
Conky: /etc/conky/conky.conf: 91: no such configuration: '--'
Conky: /etc/conky/conky.conf: 92: no such configuration: '--'
Conky: /etc/conky/conky.conf: 93: no such configuration: '--'
Conky: use_spacer should have an argument of left, right, or none.  '= 'none',' seems to be some form of 'false', so defaulting to none.
Conky: /etc/conky/conky.conf: 96: no such configuration: '--'
Conky: /etc/conky/conky.conf: 97: no such configuration: '--'
Conky: /etc/conky/conky.conf: 98: no such configuration: '--text_buffer_size'
Conky: /etc/conky/conky.conf: 100: no such configuration: '--'
Conky: /etc/conky/conky.conf: 103: no such configuration: '--'
Conky: /etc/conky/conky.conf: 106: no such configuration: '--'
Conky: /etc/conky/conky.conf: 107: no such configuration: '--'
Conky: /etc/conky/conky.conf: 110: no such configuration: '--'
Conky: /etc/conky/conky.conf: 111: no such configuration: '--'
Conky: /etc/conky/conky.conf: 112: no such configuration: '--'
Conky: /etc/conky/conky.conf: 114: no such configuration: '--'
Conky: /etc/conky/conky.conf: 115: no such configuration: '--'
Conky: /etc/conky/conky.conf: 116: no such configuration: '--'
Conky: /etc/conky/conky.conf: 119: no such configuration: '--'
Conky: /etc/conky/conky.conf: 120: no such configuration: '--'
Conky: /etc/conky/conky.conf: 121: no such configuration: '--'
Conky: /etc/conky/conky.conf: 123: no such configuration: '--'
Conky: /etc/conky/conky.conf: 124: no such configuration: '--'
Conky: /etc/conky/conky.conf: 125: no such configuration: '--'
Conky: /etc/conky/conky.conf: 126: no such configuration: '--'
Conky: /etc/conky/conky.conf: 130: no such configuration: '};'
Conky: /etc/conky/conky.conf: 132: no such configuration: 'conky.text'
Conky: /etc/conky/conky.conf: 133: no such configuration: '${alignc}${font'
Conky: /etc/conky/conky.conf: 134: no such configuration: '${font'
Conky: /etc/conky/conky.conf: 135: no such configuration: '${voffset'
Conky: /etc/conky/conky.conf: 136: no such configuration: '${time'
Conky: /etc/conky/conky.conf: 137: no such configuration: 'at'
Conky: /etc/conky/conky.conf: 138: no such configuration: '${voffset'
Conky: /etc/conky/conky.conf: 139: no such configuration: '${voffset'
Conky: /etc/conky/conky.conf: 140: no such configuration: ']];'
Conky: missing text block in configuration; exiting
***** Imlib2 Developer Warning ***** :
        This program is calling the Imlib call:

        imlib_context_free();

        With the parameter:

        context

        being NULL. Please fix your program.
[I] ╭─vistaus@solus /run/media/vistaus/MicroSD/Apps  ‹system› 
╰─$ 
```

**Comment by Vistaus** [comment]
**UPDATE**

I figured it out: it was because this conkyrc needs conky 1.10 or later, so I installed conly from the latest git master.
But I still can't fully run it as it says:

```
I] ╭─vistaus@solus /run/media/vistaus/MicroSD/Apps/conky/build  ‹system›  <master> 
╰─$ 
sh: /home/vistaus/.config/conky/flea/res/weather: Permission denied
sh: /home/vistaus/.config/conky/flea/res/weather: Permission denied
```

Even though I have full permissions to that folder. Even sudo chown -R vistaus ~/.config/conky/flea/res/weather didn't help.

**Comment by addy-dclxvi** [comment]
Yes, You need Conky 1.10 with all build options enabled. I use Debian Stretch with [conky-all](https://packages.debian.org/stretch/conky-all).
Place this repo to *~/.config/conky*

```git clone https://github.com/addy-dclxvi/Conky-Theme-Collections ~/.config/conky --depth 1```

Then ```chmod +x ~/.config/conky/flea/weather/res/weather```

Then edit the weather script. Change the API code & city code with yours.

Launch conky ```conky -c ~/.config/conky/flea/flea.conkyrc```

If the weather script cannot be executed. Try to change the shell intepreter (first line of weather script).

Possible replacement : 

- #! /bin/bash

- #! /usr/bin/bash

- #! /bin/zsh

- #! /bin/sh

Hope this helps

**Comment by Vistaus** [comment]
Thanks for your quick reply! Making the weather script executable fixed the error. However, even though I've set my API key and city code in the script, conky says "THE WEATHER IS UNKNOWN".
Also, the conky background is totally black instead of transparent.

Could you help me with these 2 issues as well? :)

**Comment by addy-dclxvi** [comment]
You're welcome! Glad it works 😊

1. Do You have `wget` package installed? Also it needs some command like `grep`, `awk`, and `tr`. Make sure the package that contains commands above is Installed. And just a reminder, make sure the API code & city code are correct.

2. It seems your Desktop Environment is not respecting the Conky "fake" transparency. Try to change some variable in the Conky configuration to enable real transparency. Possible configuration

- own_window_type normal

- own_window_argb_visual yes

- own_window_transparent no

- own_window_argb_value 50

I can't predict a correct value, because I don't have any Desktop Environment. And I can have an advantage using fake transparency on Openbox. It can be able to look transparent even I don't activate the compositor. The background of the Conky mimic the wallpaper behind it, like a chameleon.

**Comment by Vistaus** [comment]
1. All of those commands are installed and wget is installed as well (that's my go-to cli app for downloading stuff :P). I re-checked the API code and city code and they are both correct as well.

Just for reference:

```
#!/bin/bash

# I take this script from Anachron's i3blocks
# I only slightly modify this script to add an option to show icon
# I also remove the i3blocks specify script
# To make this works with tint2 executor, polybar custom script, dzen2 feeder, conkybar, lemonbar feeder, dunst notify, etc.
# 'weather -i' = with icon, 'weather' = text only
# Cheers!
# Addy

# Open Weather Map API code, register to http://openweathermap.org to get one ;)
API_KEY="fe8f049f5486b803a77f1024dd9d62cb"

# Check on http://openweathermap.org/find
CITY_ID="2754064"
```
I can confirm it's working when I go to http://api.openweathermap.org/data/2.5/weather?id=2754064&appid=fe8f049f5486b803a77f1024dd9d62cb&units=metric but conky keeps saying "The weather is unknown"

2. I'm currently using KDE. I've changed all of the settings you mentioned but still no transparency. KWin's compositor is running, so...

EDIT: never mind about 2, ARGB transparency's working now :)

**Comment by Vistaus** [comment]
I don't know how, but it seems like it's all working fine now. But what's the update interval? 'Cause it currently says that it's -1 C but the OpenWeatherMap site says it's currently -2 C at my location.

**Comment by addy-dclxvi** [comment]
Ohh, okay nevermind. Everyone know Linux is involving several kinds of black magic from the witchcraft 😅

I set the the interval to refresh every 1800 seconds. Just change the value. Open the conkyrc with text editor. Hit Ctrl+H, replace 1800 with 60 (if You want to refresh every minute). And consider to spend your winter holiday here, very warm 22°C 😋

**Comment by Vistaus** [comment]
Hmm, it now stopped working again as it again says "The weather status is unknown". Do you have any idea still? :)

Haha, I've never been to Java or Indonesia but I do really like Java and Indonesia (the food and the culture), but I don't have the money to go on such a long trip (I do prefer cold(ish) places though as my body can't stand high temperatures, although 22°C would be doable for a short vacation). If I ever do have enough money for a far-away vacation, I'll definitely go to Java! :)

**Edit: it started working again after I restarted Conky. Strange that I have to restart Conky in order to update the weather after a connection loss (I turn off internet during nighttime) but oh well :/**

Thank you very much all of your help! You reply fast and you are really nice! :smile: Closing this issue.

**Comment by Vistaus** [comment]
I actually do have one question still: why does Conky keep "redirecting the output to wget-log" which creates like 20 log files or something?

**Comment by addy-dclxvi** [comment]
Thank You very much!
Glad to help 😊

**Hmm, it now stopped working again as it again says "The weather status is unknown". Do you have any idea still? :)**

Need luck factor maybe, it's quite stable here 🤔

And thanks for the kind words about my place! But if You can't stand on high temperature, probably it's not a good idea to spent holiday here. Average temperature at day is 30°C. And when solar equinox happens, the temperature can reach almost 40°C.

**I actually do have one question still: why does Conky keep "redirecting the output to wget-log" which creates like 20 log files or something?**

The ```wget -qO-``` code theoretically should make it quiet and don't save the log as text file 🤔

And it works on Debian. I don't get any log here. But, When I tried it on Arch, logging as text file happens. I can't figure out why 🤔

Probably different ```wget``` version has different command to make it quiet.

**Comment by Vistaus** [comment]
wget --help says that -q should make it quiet, but it really doesn't :(

I'm using Solus (Linux) btw.
